version: '3.7'

networks:
    ti-docker-testing-internal:
        name: ti-docker-testing-internal

volumes:
    ti-docker-testing-database-store:
        driver: local
        name: ti-docker-testing-database-store

services:
    ti-docker-testing-app:
        container_name: ti-docker-testing-app
        build:
            context: .
            dockerfile: ./docker/ti-docker-testing-app/Dockerfile
        restart: always
        working_dir: /var/www
        volumes:
            - ./core:/var/www
        networks:
            - ti-docker-testing-internal

    ti-docker-testing-database:
        container_name: ti-docker-testing-database
        image: mysql:8.0.21
        restart: always
        volumes:
            - ti-docker-testing-database-store:/var/lib/mysql
        networks:
            - ti-docker-testing-internal
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            # MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            # MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

    ti-docker-testing-webserver:
        container_name: ti-docker-testing-webserver
        image: nginx:1.19.6-alpine
        restart: always
        ports:
            - ${WEB_EXT_PORT}:80
        volumes:
            - ./core:/var/www
            - ./docker/ti-docker-testing-webserver/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - ti-docker-testing-internal
